name: suzi_app
description: "SUZI"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.4.9
  cupertino_icons: ^1.0.2
  firebase_core: ^2.24.2
  firebase_auth: ^4.16.0
  riverpod_annotation: ^2.3.3
  font_awesome_flutter: ^10.6.0
  google_sign_in: ^6.2.1
  validators: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  riverpod_generator: ^2.3.9
  riverpod_lint: ^2.3.7
  custom_lint: ^0.5.8
  build_runner: ^2.4.8

flutter:
  uses-material-design: true
  assets:
    - assets/illustrations/illustration1.png
    - assets/illustrations/illustration2.png
    - assets/illustrations/illustration3.png
    - assets/illustrations/button.png

  fonts:
    - family: Technor
      fonts:
        - asset: assets/fonts/Technor-Regular.otf
        - asset: assets/fonts/Technor-Bold.otf
          weight: 700
        - asset: assets/fonts/Technor-Black.otf
          weight: 900
    - family: Erode
      fonts:
        - asset: assets/fonts/Erode-Regular.otf
        - asset: assets/fonts/Erode-Bold.otf
          weight: 700
        - asset: assets/fonts/Erode-Italic.otf
          style: italic
  #    - family: Trajan Pro
  #      fonts:
  #        - asset: fonts/TrajanPro.ttf
  #        - asset: fonts/TrajanPro_Bold.ttf
  #          weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
