name: suzi_app
description: "SUZI"
publish_to: "none"
version: 1.0.1+2

environment:
  sdk: ">=3.2.5 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.4.9
  cupertino_icons: ^1.0.2
  firebase_core: ^2.24.2
  firebase_auth: ^4.19.0
  riverpod_annotation: ^2.3.5
  font_awesome_flutter: ^10.6.0
  google_sign_in: ^6.2.1
  validators: ^3.0.0
  http: ^1.2.0
  rive: ^0.12.4
  loading_animation_widget: ^1.2.0+4
  geolocator: ^11.0.0
  flutter_animate: ^4.5.0
  webview_flutter: ^4.5.0
  android_intent_plus: ^4.0.3
  flutter_dotenv: ^5.1.0
  flutter_native_splash: ^2.3.10
  url_launcher: ^6.2.5
  wheel_slider: ^1.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  riverpod_generator: ^2.3.9
  riverpod_lint: ^2.3.7
  custom_lint: ^0.6.4
  build_runner: ^2.4.8
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true
  assets:
    - assets/illustrations/illustration1.png
    - assets/illustrations/illustration2.png
    - assets/illustrations/illustration3.png
    - assets/illustrations/button.png
    - assets/rive/blob.riv
    - assets/rive/blob1.riv
    - assets/rive/blob2.riv
    - assets/rive/blob3.riv
    - assets/illustrations/background.png
    - assets/icons/nav1.png
    - assets/icons/nav2.png
    - assets/icons/nav1s.png
    - assets/icons/nav2s.png
    - .env
    - assets/icons/appicon.png

  fonts:
    - family: Technor
      fonts:
        - asset: assets/fonts/Technor-Regular.otf
        - asset: assets/fonts/Technor-Bold.otf
          weight: 700
        - asset: assets/fonts/Technor-Black.otf
          weight: 900
    - family: Erode
      fonts:
        - asset: assets/fonts/Erode-Regular.otf
        - asset: assets/fonts/Erode-Bold.otf
          weight: 700
        - asset: assets/fonts/Erode-Italic.otf
          style: italic
  #    - family: Trajan Pro
  #      fonts:
  #        - asset: fonts/TrajanPro.ttf
  #        - asset: fonts/TrajanPro_Bold.ttf
  #          weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icons/appicon.png"
  min_sdk_android: 21
  adaptive_icon_background: #FF4200

flutter_native_splash:
  background_image: "assets/splash.png"
  android_12:
    image: assets/icons/appicon12.png
    color: "#FF4200"
    icon_background_color: "#FF4200"
